### ISSUE TITLE
Allow cards to not be wrapped in an anchor

### ISSUE THREAD

**Issue by richardbporter** [uiowa/hds#27]
The SiteNow platform does not require a link for a card. It also allows for links/buttons in the card text. Would it be possible to wrap the card in an anchor only if the link field is set? Or would another card variant (card--unlinked...) be easier?

**Comment by bspeare** [comment]
I can wrap the card in a `{% block %}` (https://twig.symfony.com/doc/2.x/tags/block.html) tag that contains the div wrapper that we can replace in our theme.   How does that sound?

**Comment by richardbporter** [comment]
That sounds good as long as the bttn div can be hidden as well: https://github.com/uiowa/hds/blob/master/components/02%20-%20blocks/card-block/card-block--basic.twig#L21

**Comment by bspeare** [comment]
You will also probably want the `{{ card_text }}` not wrapped in markup - is that correct?

https://github.com/uiowa/hds/blob/d1f7e3cb2dbfa1ef58eed9dd3c675615f4eb656d/components/02%20-%20blocks/card-block/card-block--basic.twig#L19

**Comment by richardbporter** [comment]
Yea probably not a `<p>` tag. Would a `<div>` work there?
