### ISSUE TITLE
Adjust margin/padding for <li> elements

### ISSUE THREAD

**Issue by pyrello** [uiowa/hds#40]
Currently, the <li> dot sits outside the edge of the container. I would like to have it line up flush with the edge of the container.

<img width="306" alt="Screen Shot 2019-12-19 at 9 40 25 AM" src="https://user-images.githubusercontent.com/709009/71187084-fe21c280-2243-11ea-90de-c16245f8529c.png">

**Comment by mark-bennett-uiowa** [comment]
This is also an issue for nested lists and <li>'s. There needs to be some left-margin/padding for <ul><ul>.
![Screen Shot 2019-12-19 at 12 06 43 PM](https://user-images.githubusercontent.com/3067017/71197903-3e8b3b80-2258-11ea-8d25-ed7f2a2936cb.png)
In the above screenshot, "Tenure Track Career Path" should be a child element of "Faculty".

**Comment by mark-bennett-uiowa** [comment]
NOTE: The correct padding is visible when not logged into the site.
![Screen Shot 2019-12-20 at 3 58 49 PM](https://user-images.githubusercontent.com/3067017/71295489-a5d0ea80-2341-11ea-98f0-568c77851bb9.png)

**Comment by mark-bennett-uiowa** [comment]
See #45 for more issues with lists.
