### ISSUE TITLE
Ordered/Unordered lists not styled properly. Start="" values working?

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/hds#45]
We were adding a page to the policy site and noticed that the ordered/unordered lists were not displaying their list value properly. Also, while logged into the site, there is still the issue with proper indentation not showing. See images below:
![Screen Shot 2019-12-30 at 3 03 37 PM](https://user-images.githubusercontent.com/3067017/71600798-319eff80-2b16-11ea-943e-b35486ae5f8a.png)
This is how it looks when not logged into the site:
![Screen Shot 2019-12-30 at 3 05 34 PM](https://user-images.githubusercontent.com/3067017/71600799-3499f000-2b16-11ea-86e0-8ca6d634a534.png)

**Comment by pyrello** [comment]
Since this is a site that lives online, can you provide a link?

**Comment by mark-bennett-uiowa** [comment]
https://policy.clas.uiowa.edu/clas-policies-and-procedures/faculty/faculty-research-and-funding/book-subvention

**Comment by bspeare** [comment]
Can you turn off css aggregation on the site?

**Comment by mark-bennett-uiowa** [comment]
I turned off the CSS aggregation, and cleared the cache. Checked on Chrome and a new browser and still had the same issues.

**Comment by pyrello** [comment]
This seems to be specific to `<ol>`. On the Table of Contents page, which uses `<ul>` lists, the dots show as expected.
